name: Extraction TV Matinale

on:
  schedule:
    # Déclenchement à 4h00 UTC (6h00 du matin en France)
    - cron: '0 4 * * *'
  workflow_dispatch: # Permet de forcer manuellement

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Récupération du projet
      uses: actions/checkout@v4

    - name: Configuration de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Lancement du nettoyage des chaînes
      run: python update_tv.py

    - name: Vérification de la présence du fichier JSON
      run: ls -la

    - name: Configuration de GitHub Pages
      uses: actions/configure-pages@v4

    - name: Création et empaquetage des fichiers web
      uses: actions/upload-pages-artifact@v3
      with:
        # On spécifie explicitement de prendre tout le dossier courant (.)
        path: '.'

    - name: Déploiement direct sur GitHub Pages
      uses: actions/deploy-pages@v4
