name: Extraction TV Matinale

on:
  workflow_dispatch: # Permet uniquement un déclenchement manuel si besoin

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - name: Récupération du projet
      uses: actions/checkout@v4

    - name: Configuration de GitHub Pages
      uses: actions/configure-pages@v5

    - name: Création de l'artéfact Web
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Déploiement en ligne direct
      uses: actions/deploy-pages@v4
